name: auto PR swiftLint


on:
  pull_request:
    branches: [ develop ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      
jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      	- uses: actions/checkout@v1

      	- name: Run auto PR Swiftlint
        run: swiftlint --config .swiftlint.yml

	- name: Auto Comment
  	uses: bubkoo/auto-comment@v1
  	with:
    	GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    	pullRequestOpened: >
      	ğŸ‘‹ @{{ author }}
      
		```
      		Auto PR SwiftLint is Success!! ğŸ«¶ğŸ»
       		```
      
